---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netmaker
  name: netmaker-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmaker-ui
  template:
    metadata:
      labels:
        app: netmaker-ui
    spec:
      containers:
      - name: netmaker-ui
        image: gravitl/netmaker-ui
        ports:
        - containerPort: 443
        env:
        - name: BACKEND_URL
          value: 'https://api.nm.creometry.com'
      terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: 'netmaker-ui'
  namespace: netmaker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 'netmaker-ui'
  sessionAffinity: None
  type: 'ClusterIP'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nm-ui-ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dashboard.nm.creometry.com
    secretName: nm-ui-tls
  rules:
  - host: dashboard.nm.creometry.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netmaker-ui
            port:
              number: 80